{{- if and (eq .Values.storage.backend "s3") .Values.storage.s3.createSecret }}
{{- if .Values.storage.s3.existingSecret }}
{{- fail "storage.s3.createSecret cannot be used together with storage.s3.existingSecret" }}
{{- end }}
{{- if or (not .Values.storage.s3.accessKey) (not .Values.storage.s3.secretKey) }}
{{- fail "storage.s3.accessKey and storage.s3.secretKey are required when storage.s3.createSecret is true" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nixery.fullname" . }}-s3
  labels:
    {{- include "nixery.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $sd := dict }}
  {{- $_ := set $sd .Values.storage.s3.accessKeyKey .Values.storage.s3.accessKey }}
  {{- $_ := set $sd .Values.storage.s3.secretKeyKey .Values.storage.s3.secretKey }}
  {{- toYaml $sd | nindent 2 }}
{{- end }}
